require: rubocop-rspec
# inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Enabled: false

Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

AllCops:
  RunRailsCops: true
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
    - bower_components/**/*
 

