require: rubocop-rspec
# inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Enabled: false

Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
    - bower_components/**/*
    - 'app/pdfs/person_pdf.rb'
