language: ruby
rvm:
  - 2.0.0
  - 1.9.3
script: bundle exec rspec spec 
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database memapp_test'
#  - psql -c 'create database memapp_test' -U postgres