language: ruby
before_install:
  - gem update --system
  - gem update bundler
rvm:
#  - 1.9.3
#    gemfiles/1.9.3.gemfile
  - 2.0.0
#    - gemfiles/2.0.0.gemfile
#  - 2.1
#    - gemfiles/2.1.gemfile
#gemfile:

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

  
#env:
#  - DEFER_GC=false RAILS_EDGE=true

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/initializers/secret_token.travis.rb config/initializers/secret_token.rb
  - mysql -e 'create database memapp_test'
  - psql -c 'create database memapp_test' -U postgres
  - rake db:test:prepare
script: 
 - bundle exec rake spec
matrix:
  allow_failures:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_edge.gemfile
      env: DEFER_GC=false RAILS_EDGE=true
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
      env: DEFER_GC=false RAILS_EDGE=true
    - rvm: 2.1
      gemfile: gemfiles/rails_edge.gemfile
      env: DEFER_GC=false RAILS_EDGE=true