language: ruby
rvm:
  - 2.0.0
  -gemfile: Gemfile
  - 1.9.3
  -gemfile: gemfiles/1.9.3.gemfile
  
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/initializers/secret_token.travis.rb config/initializers/secret_token.rb
  - mysql -e 'create database memapp_test'
  - psql -c 'create database memapp_test' -U postgres
script:
 - bundle exec rake db:schema:load
 - bundle exec rake db:test:prepare
 - bundle exec rspec spec 
#gemfile:
# - gemfiles/1.9.3.gemfile
# - gemfiles/2.0.0.gemfile
 