language: ruby

before_install:
 - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
 - ./script/travis/bundle_install.sh

rvm:
  - 2.0.0

env:
  matrix:
  - DB=sqlite
  global:
    - RAILS_ENV=test
    - secure: gGj4X5f+JryM6XoouLs7xt3jHWnKPW4gAHyW4QhYb4DLyGGg/LpjNH051UAlUkrqpvT68/X594czIzXYAujmESnjkK2dnPaHKTF+/d3OChEIfCPhO8qCHVyFJyDcPE4IYHLCwvn4wV6a/IakKYKJujwJn6oJrEVbKwaFte9tlCg=

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/initializers/secret_token.travis.rb config/initializers/secret_token.rb
  - mysql -e 'create database memapp_test'
  - psql -c 'create database memapp_test' -U postgres
  - touch db/test.sqlite3

after_script:
  - ruby script/travis/bundle_cache.rb

notifications:
  email: false
  
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake spec