bundler_args: --without development --path=~/.bundle
language: ruby
cache: bundler

before_install:
 - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
 - ./script/travis/bundle_install.sh

rvm:
  - 2.0.0

env:
  matrix:
  - DB=mysql
#  - DB=sqlite
#  - DB=postgresql
  global:
    - RAILS_ENV=test
    - secure: "kBO/t8X0OMCo4ix4+z9u19JHU9SBjyDlvEzrzErls1C+teLmrIbkzL8FtgaY1aZTqse3SC23H/O6s5N21WpV8aJbVF9L/DDZdC+BP6sUKl+Q8HEJ0JMFju9lhnFVTsNOXN8J+OGlVRZt0b5ofoP2pL1ZXFHAEQvRuet9HVSnYyY="

# - cp config/database.travis.yml config/database.yml
before_script:
  - cp config/database.$DB.yml config/database.yml
  - cp config/initializers/secret_token.travis.rb config/initializers/secret_token.rb
  - mysql -e 'create database memapp_$RAILS_ENV'
#  - psql -c 'create database memapp_$RAILS_ENV' -U postgres
#  - touch 'db/$RAILS_ENV.sqlite3'

after_script:
  - ruby script/travis/bundle_cache.rb

notifications:
  email: true
  
script: "bundle exec rake db:create db:test:load spec"


after_failure:
#- "mysql -e 'show databases;'"
- "cat ./config/database.yml"
- "echo $RAILS_ENV"
- "bundle exec rake --version"
