# Speed up travis builds see : https://gist.github.com/ArturT/5792488
# encrypt the ftp login see: http://docs.travis-ci.com/user/encryption-keys/

bundler_args: --without development --path=~/.bundle
language: ruby
cache: bundler

before_install:
 - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
 - ./script/travis/bundle_install.sh

rvm:
  - 2.0.0

env:
  matrix:
  - DB=mysql
#  - DB=sqlite
#  - DB=postgresql
  global:
    - RAILS_ENV=test
    - secure: Wk3Sl0mcOYADwa9J7dtt+lnWiGftVD0sNr04raa/IybH8+D/j1DHbrD+MmmkJgSNIje/bn8zOmPYkhn++8ynTOhqlAUDaHv/RWQdy89N9QhzOME9fEHTiswYWKu1sy3wvZT9OeKN2n+W4qVUnmY01VN+vdR/duqjtvmY9Bxr5yU=

# - cp config/database.travis.yml config/database.yml
before_script:
  - cp config/database.$DB.yml config/database.yml
  - cp config/initializers/secret_token.travis.rb config/initializers/secret_token.rb
  - mysql -e 'create database memapp_$RAILS_ENV'
#  - psql -c 'create database memapp_$RAILS_ENV' -U postgres
#  - touch 'db/$RAILS_ENV.sqlite3'

after_script:
  - ruby script/travis/bundle_cache.rb

addons:
  - code_climate:
      - repo_token:
        - secure: XF1pHDHcZMdsMuW4mTtmyz4Qx0TlMeg0XL1NhUkWniQo4d++Zim74oi47Av2kHtJ8x9JX8k9QVQaNkUFxUJo3w8V2CpPQHp6I6RyJhp04s4jECnF10j92hMeDboTs89mh8tF0lTLwHGgqTac3IFvoIK6iwoqGKkZ8zhiF41NyaA=


notifications:
  email: true
  
script: "bundle exec rake db:create db:test:load spec"


after_failure:
- "mysql -e 'show databases;'"
- "cat ./config/database.yml"
- "echo $RAILS_ENV"
- "bundle exec rake --version"
