# Speed up travis builds see : https://gist.github.com/ArturT/5792488
# encrypt the ftp login see: http://docs.travis-ci.com/user/encryption-keys/
# travis encrypt CI_FTP_URL="ftp-app.example.com" CI_FTP_HOST="ftp.example.com" CI_FTP_USER="YOUR_FTP_USER" CI_FTP_PASS="YOUR_FTP_PASSWORD"


bundler_args: --without development --path=~/.bundle
language: ruby

install:
  - gem uninstall bundler
  - gem install bundler --version '1.8.0'


cache: bundler

before_install:
 - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
 - ./script/travis/bundle_install.sh

rvm:
  - 2.0.0

env:
  matrix:
  - DB=mysql
#  - DB=sqlite
#  - DB=postgresql
  global:
    - RAILS_ENV=test
    - BUNDLE_ARCHIVE='CACHE_$TRAVIS_BRANCH'
    - secure: "gEVIoM2ItXmMWhvHmBsfwDpom27JiiLZIuMXpguffDEMpSaYOFXpaKWBPhq3tN0Ocfb3CKBEiP9AWdQKqz+6ssXw81r/ge2eSczL92WHspmoyQhWPqjnlpJACJf6kVXjYuxqYQl0NkOAN/bbrC/54jd9Yl6Csm51hCr1u5jowrM="

# - cp config/database.travis.yml config/database.yml
before_script:
  - cp config/database.$DB.yml config/database.yml
  - cp config/initializers/secret_token.travis.rb config/initializers/secret_token.rb
  - mysql -e 'create database memapp_$RAILS_ENV'
#  - psql -c 'create database memapp_$RAILS_ENV' -U postgres
#  - touch 'db/$RAILS_ENV.sqlite3'

after_script:
  - ruby script/travis/bundle_cache.rb

addons:
  - code_climate:
      - repo_token:
        - secure: XF1pHDHcZMdsMuW4mTtmyz4Qx0TlMeg0XL1NhUkWniQo4d++Zim74oi47Av2kHtJ8x9JX8k9QVQaNkUFxUJo3w8V2CpPQHp6I6RyJhp04s4jECnF10j92hMeDboTs89mh8tF0lTLwHGgqTac3IFvoIK6iwoqGKkZ8zhiF41NyaA=


notifications:
  email: true
  
script: "bundle exec rake db:create db:test:load spec"


after_failure:
- "mysql -e 'show databases;'"
- "cat ./config/database.yml"
- "echo $RAILS_ENV"
- "bundle exec rake --version"
