mysql: &mysql
  adapter: mysql2
  database: memapp_<%= Rails.env %>
  username: travis
  encoding: utf8

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  database: memapp_<%= Rails.env %>
  username: travis
  encoding: utf8

sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3
 
  

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
<<: *<%= ENV['DB'] || "postgresql" %>

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults

