mysql: &mysql
  adapter: mysql2
  database: memapp_<%= Rails.env %>
  username: travis
  encoding: utf8

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  database: memapp_<%= Rails.env %>
  username: travis
  encoding: utf8


sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3
  pool: 5
  timeout: 5000
  host: localhost 
  

defaults: &defaults
<<: *<%= ENV['DB'] || "postgresql" %>


test:
  <<: *defaults

#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000
 # host: localhost 
  
development:
  <<: *defaults

production:
  <<: *defaults

