development:
  adapter: postgresql
  encoding: unicode
  database: memapp_development
  username: postgres
  encoding: utf8 
  host: 127.0.0.1 

test:
  adapter: postgresql
  encoding: unicode
  database: memapp_test
  username: postgres
  encoding: utf8 
  host: 127.0.0.1 
  
production:
  adapter: postgresql
  encoding: unicode
  database: memapp_production
  username: postgres
  encoding: utf8 
  host: 127.0.0.1 
  