require 'spec_helper'
 
# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaymenttypesController do
  before :each do
    login_user 
  end
  # This should return the minimal set of attributes required to create a valid
  # Paymenttype. As you add validations to Paymenttype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaymenttypesController. Be sure to keep this updated too.
#  let(:valid_session) { {} }
  let(:valid_session) { {"warden.user.user.key" => session["warden.user.user.key"]} }


  describe "GET index" do
    it "assigns all paymenttypes as @paymenttypes" do
      paymenttype = Paymenttype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:paymenttypes).should eq([paymenttype])
    end
  end

  describe "GET show" do
    it "assigns the requested paymenttype as @paymenttype" do
      paymenttype = Paymenttype.create! valid_attributes
      get :show, {:id => paymenttype.to_param}, valid_session
      assigns(:paymenttype).should eq(paymenttype)
    end
  end

  describe "GET new" do
    it "assigns a new paymenttype as @paymenttype" do
      get :new, {}, valid_session
      assigns(:paymenttype).should be_a_new(Paymenttype)
    end
  end

  describe "GET edit" do
    it "assigns the requested paymenttype as @paymenttype" do
      paymenttype = Paymenttype.create! valid_attributes
      get :edit, {:id => paymenttype.to_param}, valid_session
      assigns(:paymenttype).should eq(paymenttype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Paymenttype" do
        expect {
          post :create, {:paymenttype => valid_attributes}, valid_session
        }.to change(Paymenttype, :count).by(1)
      end

      it "assigns a newly created paymenttype as @paymenttype" do
        post :create, {:paymenttype => valid_attributes}, valid_session
        assigns(:paymenttype).should be_a(Paymenttype)
        assigns(:paymenttype).should be_persisted
      end

      it "redirects to the created paymenttype" do
        post :create, {:paymenttype => valid_attributes}, valid_session
        response.should redirect_to(Paymenttype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paymenttype as @paymenttype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Paymenttype.any_instance.stub(:save).and_return(false)
        post :create, {:paymenttype => { "name" => "invalid value" }}, valid_session
        assigns(:paymenttype).should be_a_new(Paymenttype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Paymenttype.any_instance.stub(:save).and_return(false)
        post :create, {:paymenttype => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested paymenttype" do
        paymenttype = Paymenttype.create! valid_attributes
        # Assuming there are no other paymenttypes in the database, this
        # specifies that the Paymenttype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Paymenttype.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => paymenttype.to_param, :paymenttype => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested paymenttype as @paymenttype" do
        paymenttype = Paymenttype.create! valid_attributes
        put :update, {:id => paymenttype.to_param, :paymenttype => valid_attributes}, valid_session
        assigns(:paymenttype).should eq(paymenttype)
      end

      it "redirects to the paymenttype" do
        paymenttype = Paymenttype.create! valid_attributes
        put :update, {:id => paymenttype.to_param, :paymenttype => valid_attributes}, valid_session
        response.should redirect_to(paymenttype)
      end
    end

    describe "with invalid params" do
      it "assigns the paymenttype as @paymenttype" do
        paymenttype = Paymenttype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Paymenttype.any_instance.stub(:save).and_return(false)
        put :update, {:id => paymenttype.to_param, :paymenttype => { "name" => "invalid value" }}, valid_session
        assigns(:paymenttype).should eq(paymenttype)
      end

      it "re-renders the 'edit' template" do
        paymenttype = Paymenttype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Paymenttype.any_instance.stub(:save).and_return(false)
        put :update, {:id => paymenttype.to_param, :paymenttype => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paymenttype" do
      paymenttype = Paymenttype.create! valid_attributes
      expect {
        delete :destroy, {:id => paymenttype.to_param}, valid_session
      }.to change(Paymenttype, :count).by(-1)
    end

    it "redirects to the paymenttypes list" do
      paymenttype = Paymenttype.create! valid_attributes
      delete :destroy, {:id => paymenttype.to_param}, valid_session
      response.should redirect_to(paymenttypes_url)
    end
  end

end
